run:
  timeout: 5m
  go: '1.21'

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - errcheck
    - typecheck
    - gosec
    - unconvert
    - gocyclo
    - misspell
    - revive
    - gocritic

linters-settings:
  gocyclo:
    min-complexity: 15
  
  govet:
    enable-all: true
  
  revive:
    rules:
      - name: exported
        disabled: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
